on:
  workflow_dispatch:
  inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

jobs:
  live streaming:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.username }}
      - name: install ffmpeg
        run: sudo apt install ffmpeg
      - name: live stream
        run: ffmpeg -re -user_agent "Mozilla/5.0" -i "https://token-media-001-vidio-com.vidiocdn.net/uploads/8270130/edge-cache-token=Expires=1720780585&KeyName=tokenized-media-vidio-com-keyset&Signature=m4dZMUbTkadNic_Xy5Bg3b1VaNIWZPuQ39eLt4YZQ9lR8Kqs10oX3lUm9e0NVR-TN15IzvUZcJafyZKV-At7Bg==/etsvod_ETS246d1f4daf2a73cfa_premier.m3u8" -c copy -f flv rtmps://fa723fc1b171.global-contribute.live-video.net:443/app/sk_us-west-2_xFRVgfONJY7d_jWpOnJNiy39EYsXoEXsAyu7i7UxDlA
